openapi: "3.1.0"
info:
  title: OpenAPI Generator repro
  version: "1.0"
paths:
  /:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  configuration:
                    type: string
